version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress2019!!!!!
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpressadmin
       MYSQL_PASSWORD: wordpress2019!!!!!

   wordpress:
     depends_on:
       - db
     image: microsoft/multicontainerwordpress
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpressadmin
       WORDPRESS_DB_PASSWORD: wordpress2019!!!!!
volumes:
    db_data:
